"""add user_id to hotel_image

Revision ID: 2b970a615ba6
Revises: 4e3b28b6a008
Create Date: 2026-02-09 14:32:37.481225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b970a615ba6'
down_revision: Union[str, Sequence[str], None] = '4e3b28b6a008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel_image', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'hotel_image', 'profile', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotel_image', type_='foreignkey')
    op.drop_column('hotel_image', 'user_id')
    # ### end Alembic commands ###
